/* ========== REVISION MODULE ========== */
/* Part 3/7 — REV + SYL extracted from inline */

var REV=(function(){var pendingRev=null,revDiff='medium';
function fillFilter(){var revs=D.getRevs().filter(function(r){return r.active});var subjs=[...new Set(revs.map(function(r){return r.subj}))].sort();var el=document.getElementById('revFilter'),val=el.value;el.innerHTML='<option value="">All Subjects</option>'+subjs.map(function(s){return'<option'+(s===val?' selected':'')+'>'+esc(s)+'</option>'}).join('')}
function render(){fillFilter();var filter=document.getElementById('revFilter').value;var revs=D.getRevs().filter(function(r){return r.active&&(!filter||r.subj===filter)});var today=D.todayKey();var tom=new Date();tom.setDate(tom.getDate()+1);var tomK=D.todayKey(tom);var groups={overdue:{},today:{},tomorrow:{},upcoming:{}};revs.forEach(function(r){var b;if(r.nextDate<today)b='overdue';else if(r.nextDate===today)b='today';else if(r.nextDate===tomK)b='tomorrow';else{var nd=new Date(r.nextDate),d=Math.ceil((nd-new Date(today))/(864e5));if(d<=14)b='upcoming';else return}if(!groups[b][r.subj])groups[b][r.subj]=[];groups[b][r.subj].push(r)});
['overdue','today','tomorrow','upcoming'].forEach(function(bk){var elId=bk==='overdue'?'revOverdue':bk==='today'?'revToday':bk==='tomorrow'?'revTomorrow':'revUpcoming';var el=document.getElementById(elId);var subjs=Object.keys(groups[bk]).sort();if(!subjs.length){el.innerHTML='<div class="empty"><p>'+(bk==='today'?'All clear! 🎉':'None')+'</p></div>';return}var h='';subjs.forEach(function(subj){var items=groups[bk][subj];h+='<div class="rg"><div class="rg-hdr" onclick="this.nextElementSibling.classList.toggle(\'hidden\')"><span class="rg-subj">'+esc(subj)+'</span><span class="rg-count">'+items.length+' topic'+(items.length>1?'s':'')+'</span></div><div class="rg-body">';items.forEach(function(r){h+=revCard(r,bk)});h+='</div></div>'});el.innerHTML=h});renderTimeline(filter)}
function revCard(r,cls){var today=D.todayKey(),nd=new Date(r.nextDate),d2=Math.ceil((nd-new Date(today))/(864e5));var wt='',wc='';if(cls==='overdue'){wt=Math.abs(d2)+'d overdue';wc='overdue'}else if(cls==='today'){wt='Today';wc='today'}else if(cls==='tomorrow'){wt='Tomorrow';wc='tomorrow'}else{wt='In '+d2+'d';wc='upcoming'}var h='<div class="rev-card '+(cls==='overdue'?'overdue':cls==='today'?'due-today':cls==='tomorrow'?'due-soon':'')+'"><div class="rev-hdr"><span class="rev-subj">'+esc(r.subj)+'</span><span class="rev-when '+wc+'">'+wt+'</span></div><div class="rev-topic">'+esc(r.topic)+'</div><div class="rev-meta">Rev #'+(r.revCount+1)+' · <span class="diff-'+r.diff+'" style="padding:1px 5px;border-radius:3px;font-size:.6rem;font-weight:700">'+r.diff+'</span> · studied '+UI.fdate(r.created)+'</div>';if(cls==='overdue'||cls==='today')h+='<div class="rev-actions"><button class="b b-xs b-grn" onclick="REV.markDone(\''+r.id+'\')">✅ Done</button><button class="b b-xs" onclick="REV.skip(\''+r.id+'\')">Skip</button><button class="b b-xs b-danger" onclick="REV.retire(\''+r.id+'\')">Retire</button></div>';return h+'</div>'}
function renderTimeline(filter){var revs=D.getRevs().filter(function(r){return r.active&&(!filter||r.subj===filter)});var el=document.getElementById('revTimeline'),today=D.todayKey();if(!revs.length){el.innerHTML='<div class="empty"><p>Study with topics to track</p></div>';return}var bySubj={};revs.forEach(function(r){if(!bySubj[r.subj])bySubj[r.subj]=[];bySubj[r.subj].push(r)});var h='';Object.keys(bySubj).sort().forEach(function(subj){var items=bySubj[subj].sort(function(a,b){return a.nextDate<b.nextDate?-1:1});h+='<div class="rg"><div class="rg-hdr" onclick="this.nextElementSibling.classList.toggle(\'hidden\')"><span class="rg-subj">'+esc(subj)+'</span><span class="rg-count">'+items.length+'</span></div><div class="rg-body">';items.forEach(function(r){var nd=new Date(r.nextDate),d2=Math.ceil((nd-new Date(today))/(864e5));var st=d2<0?Math.abs(d2)+'d overdue':d2===0?'today':'in '+d2+'d';var sc=d2<0?'color:var(--red)':d2===0?'color:var(--acc)':'color:var(--grn)';h+='<div style="display:flex;align-items:center;gap:6px;padding:5px 0;border-bottom:1px solid var(--brd);font-size:.73rem"><span class="diff-'+r.diff+'" style="padding:1px 5px;border-radius:3px;font-size:.55rem;font-weight:700;min-width:44px;text-align:center">'+r.diff+'</span><span style="flex:1;font-weight:600;color:var(--heading)">'+esc(r.topic)+'</span><span style="font-family:JetBrains Mono,monospace;font-weight:700;font-size:.68rem;'+sc+'">'+st+'</span></div>'});h+='</div></div>'});el.innerHTML=h}
function markDone(id){pendingRev=id;revDiff='medium';var r=D.getRevs().find(function(x){return x.id===id});document.getElementById('revModalTopic').textContent=r.subj+' → '+r.topic;document.querySelectorAll('#revDiffSel .diff-btn').forEach(function(b){b.classList.remove('on')});document.querySelectorAll('#revDiffSel .diff-btn')[1].classList.add('on');document.getElementById('revModal').classList.remove('hidden')}
function setRevDiff(d){revDiff=d;document.querySelectorAll('#revDiffSel .diff-btn').forEach(function(b){b.classList.remove('on');if(b.textContent.toLowerCase().indexOf(d)>=0)b.classList.add('on')})}
function confirmRev(){if(!pendingRev)return;var revs=D.getRevs(),r=revs.find(function(x){return x.id===pendingRev});if(!r)return;r.revCount++;r.diff=revDiff;r.history.push({date:D.todayKey(),diff:revDiff,type:'rev #'+r.revCount});var days=SR[revDiff]||SR.hard;var idx=Math.min(r.revCount,days.length-1);var nd=new Date();nd.setDate(nd.getDate()+days[idx]);r.nextDate=D.todayKey(nd);D.setRevs(revs);document.getElementById('revModal').classList.add('hidden');UI.toast('Next: '+UI.fdate(r.nextDate)+' ('+days[idx]+'d)');render();D.push();pendingRev=null}
function skip(id){var revs=D.getRevs(),r=revs.find(function(x){return x.id===id});if(!r)return;var tom=new Date();tom.setDate(tom.getDate()+1);r.nextDate=D.todayKey(tom);D.setRevs(revs);render();D.push();UI.toast('Skipped')}
function retire(id){if(!confirm('Retire?'))return;var revs=D.getRevs(),r=revs.find(function(x){return x.id===id});if(r)r.active=false;D.setRevs(revs);render();D.push()}
return{render:render,markDone:markDone,setRevDiff:setRevDiff,confirmRev:confirmRev,skip:skip,retire:retire}})();


/* ========== SYLLABUS MODULE ========== */
var SYL=(function(){var setupSubjName='';
function setupSubj(){var s=document.getElementById('sylSubj').value;if(!s){UI.toast('Select subject');return}setupSubjName=s;document.getElementById('sylMT').textContent='Lectures: '+s;var syl=D.getSyl();document.getElementById('sylLecCount').value=syl[s]&&syl[s].total?syl[s].total:'';document.getElementById('sylModal').classList.remove('hidden')}
function saveSetup(){var n=parseInt(document.getElementById('sylLecCount').value)||0;if(n<1){UI.toast('Enter count');return}var syl=D.getSyl();if(!syl[setupSubjName])syl[setupSubjName]={};syl[setupSubjName].total=n;if(!syl[setupSubjName].done)syl[setupSubjName].done=0;D.setSyl(syl);document.getElementById('sylModal').classList.add('hidden');renderAll();D.push();UI.toast('Saved')}
function closeSetup(){document.getElementById('sylModal').classList.add('hidden')}
function toggleLec(subj,idx){var syl=D.getSyl();if(!syl[subj])return;syl[subj].done=idx<syl[subj].done?idx:idx+1;D.setSyl(syl);renderAll();D.push()}
function getTopicsForSubj(subj){var revs=D.getRevs().filter(function(r){return r.subj===subj});var today=D.todayKey();return revs.map(function(r){var nd=new Date(r.nextDate),d2=Math.ceil((nd-new Date(today))/(864e5));var st=!r.active?'retired':d2<0?Math.abs(d2)+'d overdue':d2===0?'today':'in '+d2+'d';var sc=!r.active?'var(--tf)':d2<0?'var(--red)':d2===0?'var(--acc)':'var(--grn)';return{topic:r.topic,date:r.created,diff:r.diff,status:st,color:sc,active:r.active}})}
function renderAll(){var syl=D.getSyl(),cfg=D.getCfg();var el=document.getElementById('sylList');var subjs=cfg.studySubjects;if(!subjs.length){el.innerHTML='<div class="empty"><p>Add subjects in settings</p></div>';return}var h='';subjs.forEach(function(subj){var s=syl[subj];var topics=getTopicsForSubj(subj);var hasLectures=s&&s.total;var pct=hasLectures?Math.round((s.done||0)/s.total*100):0;
h+='<div class="syl-card"><div class="syl-hdr"><span class="syl-subj">'+esc(subj)+'</span>';
if(hasLectures)h+='<span class="syl-pct">'+pct+'%</span>';
h+='</div>';
if(hasLectures){h+='<div class="syl-bar"><div class="syl-bar-fill" style="width:'+pct+'%"></div></div><div class="syl-info">Lectures: '+(s.done||0)+'/'+s.total+'</div><div class="syl-lec-btns">';for(var i=0;i<Math.min(s.total,100);i++)h+='<button class="syl-lec-btn'+(i<(s.done||0)?' done':'')+'" onclick="SYL.toggleLec(\''+esc(subj)+'\','+i+')">'+(i+1)+'</button>';h+='</div>'}
if(topics.length){var tid='syl-topics-'+subj.replace(/[^a-zA-Z0-9]/g,'_');h+='<button class="syl-topics-btn" onclick="document.getElementById(\''+tid+'\').classList.toggle(\'hidden\')">📝 '+topics.length+' topic'+(topics.length>1?'s':'')+' studied — tap to view</button>';h+='<div class="syl-topic-list hidden" id="'+tid+'">';topics.forEach(function(t){h+='<div class="syl-topic-item"><span class="syl-topic-name">'+esc(t.topic)+'</span><span class="diff-'+t.diff+'" style="padding:1px 5px;border-radius:3px;font-size:.55rem;font-weight:700">'+t.diff+'</span><span class="syl-topic-date">'+UI.fdate(t.date)+'</span><span class="syl-topic-rev" style="color:'+t.color+';font-weight:700;font-size:.6rem">'+t.status+'</span></div>'});h+='</div>'}else if(!hasLectures){h+='<div class="syl-info" style="color:var(--tf)">No lectures set up · No topics studied yet</div>'}
h+='</div>'});el.innerHTML=h}
return{setupSubj:setupSubj,saveSetup:saveSetup,closeSetup:closeSetup,toggleLec:toggleLec,renderAll:renderAll}})();
