/* Data layer extracted from V2 project */
/* HTML escape helper — prevents XSS when rendering user input */
function esc(s){if(!s)return'';return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;')}
var QUOTES=["Work the hardest, be the smartest.","Keep working hard — results will show.","Give it your all. Every single day.","Be happy. You deserve it. 😊","Discipline is choosing between what you want now and what you want most.","The pain of discipline weighs ounces; the pain of regret weighs tons.","You didn't come this far to only come this far.","Small daily improvements lead to stunning results.","Don't stop when you're tired. Stop when you're done.","Your future self will thank you for the work you put in today.","Consistency beats talent when talent doesn't work hard.","Stay hungry. Stay foolish. Stay kind.","Remember to breathe and be happy — you're doing great. 🌟"];

var D=(function(){var SK='st3_d',GK='st3_g',TK='st3_t',GF='study_timer_v3.json';var DEF={config:{studySubjects:['Polity','History','Geography','Economics','Science','Math','English','Current Affairs','GK','Reasoning','Other'],workCategories:['Room Cleaning','Cooking','Exercise','Office Work','Errands','Personal Project','Reading','Grocery','Laundry','Other'],theme:'dark',dailyGoals:{'default':6},bedtime:22.5,effectiveMins:50,wakeTime:6,recurringTypes:['Birthdays','Anniversaries','Habits','Bills','Custom'],goalPresets:[{id:'gp_office',name:'Office Day',hours:3,days:[1,2,3,4,5],weekPattern:'all',active:true},{id:'gp_wfh',name:'WFH',hours:5.5,days:[],weekPattern:'all',active:false},{id:'gp_evensat',name:'Even Saturday',hours:7,days:[6],weekPattern:'even',active:true},{id:'gp_fullday',name:'Full Day',hours:13,days:[0],weekPattern:'all',active:true}]},deadlines:[],study:{},work:{},syllabus:{},revisions:[],recurring:[],recurringDone:{}};function gl(){try{var d=JSON.parse(localStorage.getItem(SK));if(!d||!d.config)return cp(DEF);if(!d.revisions)d.revisions=[];return d}catch(e){return cp(DEF)}}function sl(d){localStorage.setItem(SK,JSON.stringify(d))}function cp(o){return JSON.parse(JSON.stringify(o))}function gid(){return localStorage.getItem(GK)||''}function sgid(v){localStorage.setItem(GK,v)}function tok(){return localStorage.getItem(TK)||''}function stok(v){localStorage.setItem(TK,v)}function cloud(){return !!(tok()&&gid())}function tk(d){d=d||new Date();return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')}function getSess(t,dk){var d=gl();return(d[t]&&d[t][dk])||[]}function todayS(t){return getSess(t,tk())}function addS(type,dk,s){var d=gl();if(!d[type])d[type]={};if(!d[type][dk])d[type][dk]=[];d[type][dk].push(s);sl(d)}function delS(type,i){var d=gl(),k=tk();if(d[type]&&d[type][k]){d[type][k].splice(i,1);if(!d[type][k].length)delete d[type][k];sl(d)}}function getCfg(){return gl().config||cp(DEF.config)}function setCfg(c){var d=gl();d.config=c;sl(d)}function getDL(){return gl().deadlines||[]}function setDL(a){var d=gl();d.deadlines=a;sl(d)}function getSyl(){return gl().syllabus||{}}function setSyl(s){var d=gl();d.syllabus=s;sl(d)}function getRevs(){return gl().revisions||[]}function setRevs(r){var d=gl();d.revisions=r;sl(d)}function addRev(r){var d=gl();if(!d.revisions)d.revisions=[];d.revisions.push(r);sl(d)}
function getRC(){return gl().recurring||[]}function setRC(r){var d=gl();d.recurring=r;sl(d)}function addRC(r){var d=gl();if(!d.recurring)d.recurring=[];d.recurring.push(r);sl(d)}
function getRCDone(){return gl().recurringDone||{}}function setRCDone(x){var d=gl();d.recurringDone=x;sl(d)}function markRCDone(id){var d=gl(),today=tk();if(!d.recurringDone)d.recurringDone={};if(!d.recurringDone[today])d.recurringDone[today]=[];if(d.recurringDone[today].indexOf(id)===-1)d.recurringDone[today].push(id);sl(d)}
/* Recursive todo list merge — deduplicates by id, merges children recursively */
function _mergeTodoList(local,remote){var byId={};var order=[];local.forEach(function(it){byId[it.id]=cp(it);order.push(it.id)});remote.forEach(function(it){if(!byId[it.id]){byId[it.id]=cp(it);order.push(it.id)}else{var ex=byId[it.id];if(it.status==='done'&&ex.status!=='done'){ex.status='done';ex.completedAt=it.completedAt}if(it.children&&it.children.length){if(!ex.children)ex.children=[];ex.children=_mergeTodoList(ex.children,it.children)}}});return order.map(function(id){return byId[id]})}
function merge(a,b){var m=cp(a);if(b.config){if(b.config.studySubjects)m.config.studySubjects=Array.from(new Set((m.config.studySubjects||[]).concat(b.config.studySubjects)));if(b.config.workCategories)m.config.workCategories=Array.from(new Set((m.config.workCategories||[]).concat(b.config.workCategories)));if(b.config.dailyGoals)Object.assign(m.config.dailyGoals||(m.config.dailyGoals={}),b.config.dailyGoals)}if(b.deadlines){var ids=new Set((m.deadlines||[]).map(function(x){return x.id}));(b.deadlines||[]).forEach(function(x){if(!ids.has(x.id))m.deadlines.push(x)})}if(b.revisions){var rids=new Set((m.revisions||[]).map(function(x){return x.id}));(b.revisions||[]).forEach(function(x){if(!rids.has(x.id))m.revisions.push(x)})}if(b.syllabus){if(!m.syllabus)m.syllabus={};Object.keys(b.syllabus).forEach(function(k){if(!m.syllabus[k])m.syllabus[k]=b.syllabus[k]})}if(b.recurring){if(!m.recurring)m.recurring=[];var rcids=new Set(m.recurring.map(function(x){return x.id}));(b.recurring||[]).forEach(function(x){if(!rcids.has(x.id))m.recurring.push(x)})}if(b.config&&b.config.recurringTypes){m.config.recurringTypes=Array.from(new Set((m.config.recurringTypes||[]).concat(b.config.recurringTypes)))}['study','work'].forEach(function(t){if(b[t]){if(!m[t])m[t]={};Object.keys(b[t]).forEach(function(k){if(!m[t][k])m[t][k]=b[t][k];else{var ends={};m[t][k].forEach(function(s){ends[s.end]=1});b[t][k].forEach(function(s){if(!ends[s.end])m[t][k].push(s)})}})}});
/* Plans: per-item ID merge within each date key */
if(b.plans){if(!m.plans)m.plans={};Object.keys(b.plans).forEach(function(k){if(!m.plans[k]){m.plans[k]=b.plans[k]}else{var ids=new Set(m.plans[k].map(function(p){return p.id}));b.plans[k].forEach(function(p){if(!ids.has(p.id))m.plans[k].push(p)})}})}
/* Todos: recursive per-item ID merge */
if(b.todos){if(!m.todos)m.todos={};['study','work'].forEach(function(g){if(!b.todos[g])return;if(!m.todos[g]){m.todos[g]=b.todos[g]}else{m.todos[g]=_mergeTodoList(m.todos[g],b.todos[g])}})}
/* Journal: per-date merge, keeping most complete entry */
if(b.journal){if(!m.journal)m.journal={};Object.keys(b.journal).forEach(function(k){if(!m.journal[k]){m.journal[k]=b.journal[k]}else{var le=m.journal[k],re=b.journal[k];if(!le.rating&&re.rating)le.rating=re.rating;if(!le.mood&&re.mood)le.mood=re.mood;if(!le.dayType&&re.dayType)le.dayType=re.dayType;if(!le.wentRight&&re.wentRight)le.wentRight=re.wentRight;if(!le.wentWrong&&re.wentWrong)le.wentWrong=re.wentWrong;if(!le.notes&&re.notes)le.notes=re.notes;if(re.tags){if(!le.tags)le.tags=[];le.tags=Array.from(new Set(le.tags.concat(re.tags)))}}})}
return m}
function hdr(){return{'Authorization':'Bearer '+tok(),'Content-Type':'application/json','Accept':'application/vnd.github+json'}}function findG(){return fetch('https://api.github.com/gists',{headers:hdr()}).then(function(r){if(!r.ok)throw r;return r.json()}).then(function(gs){for(var i=0;i<gs.length;i++)if(gs[i].files&&gs[i].files[GF])return gs[i].id;return null})}function makeG(){var f={};f[GF]={content:JSON.stringify(gl(),null,2)};return fetch('https://api.github.com/gists',{method:'POST',headers:hdr(),body:JSON.stringify({description:'Study Timer v3',public:false,files:f})}).then(function(r){if(!r.ok)throw r;return r.json()}).then(function(g){return g.id})}function getG(){var id=gid();if(!id)return Promise.resolve(null);return fetch('https://api.github.com/gists/'+id,{headers:hdr()}).then(function(r){if(!r.ok)throw r;return r.json()}).then(function(g){var c=g.files&&g.files[GF]&&g.files[GF].content;return c?JSON.parse(c):null})}function putG(d){var id=gid();if(!id)return Promise.resolve();var f={};f[GF]={content:JSON.stringify(d,null,2)};return fetch('https://api.github.com/gists/'+id,{method:'PATCH',headers:hdr(),body:JSON.stringify({files:f})}).then(function(r){if(!r.ok)throw r})}function sync(){if(!cloud())return Promise.resolve(false);return getG().then(function(r){if(r){var m=merge(gl(),r);sl(m);return putG(m)}return putG(gl())}).then(function(){return true})}function push(){if(!cloud())return Promise.resolve();return putG(gl()).catch(function(e){console.error(e)})}function autoConn(){if(!tok())return Promise.reject('No token');return findG().then(function(id){if(id){sgid(id);return sync()}return makeG().then(function(nid){sgid(nid);return true})})}function validate(t){return fetch('https://api.github.com/gists',{headers:{'Authorization':'Bearer '+t,'Accept':'application/vnd.github+json'}}).then(function(r){if(!r.ok)throw r;return r.json()}).then(function(gs){for(var i=0;i<gs.length;i++)if(gs[i].files&&gs[i].files[GF])return gs[i].id;return null})}
function exportJSON(){var b=new Blob([JSON.stringify(gl(),null,2)],{type:'application/json'});var a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='study-timer-'+tk()+'.json';a.click();UI.toast('Exported ✓')}function trigImp(){document.getElementById('fIn').click()}function doImp(e){var f=e.target.files[0];if(!f)return;var r=new FileReader();r.onload=function(ev){try{var m=merge(gl(),JSON.parse(ev.target.result));sl(m);UI.renderAll();UI.toast('Imported ✓');push()}catch(err){UI.toast('Invalid file')}};r.readAsText(f);e.target.value=''}function clearAll(){if(!confirm('Delete ALL data?'))return;if(!confirm('Really sure?'))return;localStorage.removeItem(SK);sl(cp(DEF));UI.renderAll();UI.toast('Cleared');push()}function disc(){localStorage.removeItem(TK);localStorage.removeItem(GK)}
/* Goal lookup: manual override → preset rules → default */
function getGoalForDate(dk){
var cfg=gl().config||{};
/* 1. Manual override for specific date */
if(cfg.dailyGoals&&cfg.dailyGoals[dk]!==undefined)return cfg.dailyGoals[dk];
/* 2. Preset rules — last match wins (more specific presets go later) */
var d=new Date(dk+'T12:00:00');var dow=d.getDay();
var presets=cfg.goalPresets||[];var match=null;
for(var i=0;i<presets.length;i++){
var p=presets[i];if(!p.active)continue;
if(p.days.indexOf(dow)===-1)continue;
/* weekPattern: 'all'=every, 'even'=2nd/4th of month, 'odd'=1st/3rd/5th */
if(p.weekPattern&&p.weekPattern!=='all'){
var nth=Math.ceil(d.getDate()/7);
if(p.weekPattern==='even'&&nth%2!==0)continue;
if(p.weekPattern==='odd'&&nth%2!==1)continue;
}
match=p.hours;
}
if(match!==null)return match;
/* 3. Default fallback */
return(cfg.dailyGoals&&cfg.dailyGoals['default'])||6;
}
return{getLocal:gl,saveLocal:sl,todayKey:tk,getSess:getSess,todayS:todayS,addSession:addS,deleteSession:delS,getCfg:getCfg,setCfg:setCfg,getDL:getDL,setDL:setDL,getSyl:getSyl,setSyl:setSyl,getRevs:getRevs,setRevs:setRevs,addRev:addRev,getRC:getRC,setRC:setRC,addRC:addRC,getRCDone:getRCDone,setRCDone:setRCDone,markRCDone:markRCDone,getGistId:gid,setGistId:sgid,setToken:stok,getToken:tok,isCloud:cloud,autoConn:autoConn,sync:sync,push:push,validate:validate,makeG:makeG,exportJSON:exportJSON,trigImp:trigImp,doImp:doImp,clearAll:clearAll,disc:disc,getGoalForDate:getGoalForDate}})();
